import Head from 'next/head'
import Prismic from "prismic-javascript"
import { Client } from '../prismic-configuration'
import Link from 'next/link'
import { RichText } from 'prismic-reactjs'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Homepage from '../components/Homepage'
export default function Home({articles}) {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Marley Spoon by Siam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage/>
      <div className='articles_container'>
      {articles.results.map((article) => (
              <div key={article.uid}>
                <Link href={`article/${article.uid}`}>
                  <li className="home_list">
                    {RichText.render(article.data.home_title)}
                  </li>
                </Link>
              </div>
            ))}


      </div>


      <Banner/>
      <Footer/>

    </div>
  )
}

export async function getServerSideProps() {
  const articles = await Client().query(
    Prismic.Predicates.at("document.type", "article")
  );
  console.log(articles)
  return {
    props: {
      articles: articles,
    },
  };
}

